# Generated by Django 4.2.6 on 2023-10-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_storage1_product_storage2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unallocated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
